language: php

php:
    - 5.6
    - 7.0
    - 7.1

before_script:
  - composer self-update
  - if [[ "$TRAVIS_PHP_VERSION" == 5* ]]; then rm composer.lock; fi;
  - composer install --dev
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update && composer update --dev; fi;

script: ./vendor/bin/phpunit

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=^3
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=^3
    - php: 7.1
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=^3
    - php: 7.1
      env: SYMFONY_VERSION=^4
    - php: 7.1
      env: SYMFONY_VERSION=dev-master@dev
    - php: 7.2
      env: SYMFONY_VERSION=3.0.*
    - php: 7.2
      env: SYMFONY_VERSION=^3
    - php: 7.2
      env: SYMFONY_VERSION=^4
    - php: 7.2
      env: SYMFONY_VERSION=dev-master@dev
  allow_failures:
    - env: SYMFONY_VERSION=dev-master@dev
